# Generated by Django 5.0.1 on 2024-02-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0007_rename_cart_orders_carts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='carts',
            new_name='cart',
        ),
    ]
